name: ChatMVC
version: ${plugin-version}
description: ${plugin-description}
api-version: ${spigot-api-version}
authors: [DPOH-VAR, MYXOMOPX]
database: false
main: ru.flinbein.chatmvc.ChatMVCPlugin

libraries:
  - org.freemarker:freemarker:2.3.31

commands:
  cmvc:
    description: Chat MVC
    aliases: ['^']
    usage: /^